sudo: required
language: java
jdk: openjdk8
services: docker
branches:
  only:
  - dev  
install:
- curl -fsSL get.nextflow.io | bash
script:
- echo "docker.enabled = true" >> nextflow.config
- sudo ./nextflow run main.nf
