sudo: required
language: java
jdk: openjdk8
services: docker
branches:
  only:
  - dev  
install:
- curl -fsSL get.nextflow.io | bash
script:
- sudo chown -R travis:travis /home/travis/
- echo "docker.enabled = true" >> nextflow.config
- ./nextflow run main.nf
